name: comment_box
description: A simple Flutter comment box for posts and products.
homepage: https://github.com/adeleyeayodeji/comment_box
version: 0.0.15

environment:
  sdk: ">=2.10.0 <3.0.0"

analyzer:
  enable-experiment:
    - non-nullable

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
